var widtha = 374;
var heighta = 307;
// var padding = { top: 10, bottom: 10, left: 10, right: 10 }
var K = 0;
var r = 0

var ssvg = 0;

var orret_g = 0

// function PP() {
//     ssvg = d3.select("#Tsne").append("svg")
//         .attr("width", widtha)
//         .attr("height", heighta)
//     // .append("g")
//     // // .attr("transform", "translate(0,100)")
//     // .attr("transform", "translate(0, 0)");
// }

var pr = [];

var coor = [];

var tcircle = 0;
var flag = -1;



// PP()



d3.json('data/Scatter/sum.json', function (coor) {
    d3.json('data/Scatter/sum1.json', function (coor1) {
        d3.json('data/Scatter/sum2.json', function (coor2) {
            d3.json('data/Scatter/sum3.json', function (coor3) {
                d3.json('data/Scatter/sum4.json', function (coor4) {
                    d3.json('data/Scatter/sum5.json', function (coor5) {
                        console.log(coor1[1][0].x)

                        ssvg = d3.select("#Tsne").append("svg")
                            .attr("width", widtha)
                            .attr("height", heighta)
                        ssvg1 = d3.select("#Tsne1").append("svg")
                            .attr("width", widtha)
                            .attr("height", heighta)
                        ssvg2 = d3.select("#Tsne2").append("svg")
                            .attr("width", widtha)
                            .attr("height", heighta)
                        ssvg3 = d3.select("#Tsne3").append("svg")
                            .attr("width", widtha)
                            .attr("height", heighta)
                        ssvg4 = d3.select("#Tsne4").append("svg")
                            .attr("width", widtha)
                            .attr("height", heighta)
                        ssvg5 = d3.select("#Tsne5").append("svg")
                            .attr("width", widtha)
                            .attr("height", heighta)

                        var padding = {
                            top: 5,
                            right: 10,
                            bottom: 5,
                            left: 10
                        };

                        var xAxisWidth = widtha - padding.right;
                        var yAxisWidth = heighta - padding.bottom;

                        var xmin = 999999,
                            xmax = -999999
                        var ymin = 999999,
                            ymax = -999999

                        for (var i = 1; i <= 20; ++i) {
                            for (var j = 0; j < 304; ++j) {
                                // console.log(coor[i][j])
                                if (parseFloat(coor[i][j].x) > xmax) xmax = parseFloat(coor[i][j].x)
                                if (parseFloat(coor[i][j].x) < xmin) xmin = parseFloat(coor[i][j].x)
                                if (parseFloat(coor[i][j].y) > ymax) ymax = parseFloat(coor[i][j].y)
                                if (parseFloat(coor[i][j].y) < ymin) ymin = parseFloat(coor[i][j].y)
                            }
                        }

                        var xScale = d3.scale.linear()
                            .domain([xmin, 1.2 * xmax])
                            .range([padding.left, xAxisWidth]);
                        var yScale = d3.scale.linear()
                            .domain([ymin, ymax])
                            .range([padding.top, yAxisWidth]);

                        var color = ['#2fe9b3', '#2f8fe9', '#c32fe9', '#e92f9c', '#2E8B57', '#e4e92f', '#FFFACD']
                        var x;
                        j = 0


                        ssvg.append("text")
                            .attr("x", padding.left + 10)
                            .attr("y", heighta - padding.bottom)
                            // .attr("dx", 15)
                            // .attr("dy", "1em")
                            .attr('fill', 'black')
                            .attr('font-size', '10px')
                            .attr('text-anchor', 'middle')
                            .attr("font-family", "courier")
                            .text("第 1 轮")
                            .transition()
                            .duration(2000)
                            .text("第 2 轮")
                            .transition()
                            .duration(2000)
                            .text("第 3 轮")
                            .transition()
                            .duration(2000)
                            .text("第 4 轮")
                            .transition()
                            .duration(2000)
                            .text("第 5 轮")
                            .transition()
                            .duration(2000)
                            .text("第 6 轮")
                            .transition()
                            .duration(2000)
                            .text("第 7 轮")
                            .transition()
                            .duration(2000)
                            .text("第 8 轮")
                            .transition()
                            .duration(2000)
                            .text("第 9 轮")
                            .transition()
                            .duration(2000)
                            .text("第 10 轮")
                            .transition()
                            .duration(2000)
                            .text("第 11 轮")
                            .transition()
                            .duration(2000)
                            .text("第 12 轮")
                            .transition()
                            .duration(2000)
                            .text("第 13 轮")
                            .transition()
                            .duration(2000)
                            .text("第 14 轮")
                            .transition()
                            .duration(2000)
                            .text("第 15 轮")
                            .transition()
                            .duration(2000)
                            .text("第 16 轮")
                            .transition()
                            .duration(2000)
                            .text("第 17 轮")
                            .transition()
                            .duration(2000)
                            .text("第 18 轮")
                            .transition()
                            .duration(2000)
                            .text("第 19 轮")
                            .transition()
                            .duration(2000)
                            .text("第 20 轮")

                        for (var j = 0; j < 304; ++j) {
                            x = ssvg.append('circle')
                                .attr("cx", padding.left + xScale(coor[1][j].x))
                                .attr("cy", yScale(coor[1][j].y))
                                .attr("r", 2)
                                .attr("fill", color[coor[1][j].label])
                                // .ease('circle')
                                .transition()
                                // .delay(500)
                                .duration(2000)
                                .attr("fill", color[coor[2][j].label])
                                .attr("cx", padding.left + xScale(coor[2][j].x))
                                .attr("cy", yScale(coor[2][j].y))
                                .transition()
                                // .delay(500)
                                .duration(2000)
                                .attr("fill", color[coor[3][j].label])
                                .attr("cx", padding.left + xScale(coor[3][j].x))
                                .attr("cy", yScale(coor[3][j].y))
                                .transition()
                                // .delay(500)
                                .duration(2000)
                                .attr("fill", color[coor[4][j].label])
                                .attr("cx", padding.left + xScale(coor[4][j].x))
                                .attr("cy", yScale(coor[4][j].y))
                                .transition()
                                // .delay(500)
                                .duration(2000)
                                .attr("fill", color[coor[5][j].label])
                                .attr("cx", padding.left + xScale(coor[5][j].x))
                                .attr("cy", yScale(coor[5][j].y))
                                .transition()
                                // .delay(500)
                                .duration(2000)
                                .attr("fill", color[coor[6][j].label])
                                .attr("cx", padding.left + xScale(coor[6][j].x))
                                .attr("cy", yScale(coor[6][j].y))
                                .transition()
                                // .delay(500)
                                .duration(2000)
                                .attr("fill", color[coor[7][j].label])
                                .attr("cx", padding.left + xScale(coor[7][j].x))
                                .attr("cy", yScale(coor[7][j].y))
                                .transition()
                                // .delay(500)
                                .duration(2000)
                                .attr("fill", color[coor[8][j].label])
                                .attr("cx", padding.left + xScale(coor[8][j].x))
                                .attr("cy", yScale(coor[8][j].y))
                                .transition()
                                // .delay(500)
                                .duration(2000)
                                .attr("fill", color[coor[9][j].label])
                                .attr("cx", padding.left + xScale(coor[9][j].x))
                                .attr("cy", yScale(coor[9][j].y))
                                .transition()
                                // .delay(500)
                                .duration(2000)
                                .attr("fill", color[coor[10][j].label])
                                .attr("cx", padding.left + xScale(coor[10][j].x))
                                .attr("cy", yScale(coor[10][j].y))
                                .transition()
                                // .delay(500)
                                .duration(2000)
                                .attr("fill", color[coor[11][j].label])
                                .attr("cx", padding.left + xScale(coor[11][j].x))
                                .attr("cy", yScale(coor[11][j].y))
                                .transition()
                                // .delay(500)
                                .duration(2000)
                                .attr("fill", color[coor[12][j].label])
                                .attr("cx", padding.left + xScale(coor[12][j].x))
                                .attr("cy", yScale(coor[12][j].y))
                                .transition()
                                // .delay(500)
                                .duration(2000)
                                .attr("fill", color[coor[13][j].label])
                                .attr("cx", padding.left + xScale(coor[13][j].x))
                                .attr("cy", yScale(coor[13][j].y))
                                .transition()
                                // .delay(500)
                                .duration(2000)
                                .attr("fill", color[coor[14][j].label])
                                .attr("cx", padding.left + xScale(coor[14][j].x))
                                .attr("cy", yScale(coor[14][j].y))
                                .transition()
                                // .delay(500)
                                .duration(2000)
                                .attr("fill", color[coor[15][j].label])
                                .attr("cx", padding.left + xScale(coor[15][j].x))
                                .attr("cy", yScale(coor[15][j].y))
                                .transition()
                                // .delay(500)
                                .duration(2000)
                                .attr("fill", color[coor[16][j].label])
                                .attr("cx", padding.left + xScale(coor[16][j].x))
                                .attr("cy", yScale(coor[16][j].y))
                                .transition()
                                // .delay(500)
                                .duration(2000)
                                .attr("fill", color[coor[17][j].label])
                                .attr("cx", padding.left + xScale(coor[17][j].x))
                                .attr("cy", yScale(coor[17][j].y))
                                .transition()
                                // .delay(500)
                                .duration(2000)
                                .attr("fill", color[coor[18][j].label])
                                .attr("cx", padding.left + xScale(coor[18][j].x))
                                .attr("cy", yScale(coor[18][j].y))
                                .transition()
                                // .delay(500)
                                .duration(2000)
                                .attr("fill", color[coor[19][j].label])
                                .attr("cx", padding.left + xScale(coor[19][j].x))
                                .attr("cy", yScale(coor[19][j].y))
                                .transition()
                                // .delay(500)
                                .duration(2000)
                                .attr("fill", color[coor[20][j].label])
                                .attr("cx", padding.left + xScale(coor[20][j].x))
                                .attr("cy", yScale(coor[20][j].y))
                        }

                        ssvg1.append("text")
                        .attr("x", padding.left + 10)
                        .attr("y", heighta - padding.bottom)
                        // .attr("dx", 15)
                        // .attr("dy", "1em")
                        .attr('fill', 'black')
                        .attr('font-size', '10px')
                        .attr('text-anchor', 'middle')
                        .attr("font-family", "courier")
                        .text("第 1 轮")
                        .transition()
                        .duration(2000)
                        .text("第 2 轮")
                        .transition()
                        .duration(2000)
                        .text("第 3 轮")
                        .transition()
                        .duration(2000)
                        .text("第 4 轮")
                        .transition()
                        .duration(2000)
                        .text("第 5 轮")
                        .transition()
                        .duration(2000)
                        .text("第 6 轮")
                        .transition()
                        .duration(2000)
                        .text("第 7 轮")
                        .transition()
                        .duration(2000)
                        .text("第 8 轮")
                        .transition()
                        .duration(2000)
                        .text("第 9 轮")
                        .transition()
                        .duration(2000)
                        .text("第 10 轮")
                        .transition()
                        .duration(2000)
                        .text("第 11 轮")
                        .transition()
                        .duration(2000)
                        .text("第 12 轮")
                        .transition()
                        .duration(2000)
                        .text("第 13 轮")
                        .transition()
                        .duration(2000)
                        .text("第 14 轮")
                        .transition()
                        .duration(2000)
                        .text("第 15 轮")
                        .transition()
                        .duration(2000)
                        .text("第 16 轮")
                        .transition()
                        .duration(2000)
                        .text("第 17 轮")
                        .transition()
                        .duration(2000)
                        .text("第 18 轮")
                        .transition()
                        .duration(2000)
                        .text("第 19 轮")
                        .transition()
                        .duration(2000)
                        .text("第 20 轮")

                    for (var j = 0; j < 60; ++j) {
                        x = ssvg1.append('circle')
                            .attr("cx", padding.left + xScale(coor1[1][j].x))
                            .attr("cy", yScale(coor1[1][j].y))
                            .attr("r", 2)
                            .attr("fill", color[coor1[1][j].label])
                            // .ease('circle')
                            .transition()
                            // .delay(500)
                            .duration(2000)
                            .attr("fill", color[coor1[2][j].label])
                            .attr("cx", padding.left + xScale(coor1[2][j].x))
                            .attr("cy", yScale(coor1[2][j].y))
                            .transition()
                            // .delay(500)
                            .duration(2000)
                            .attr("fill", color[coor1[3][j].label])
                            .attr("cx", padding.left + xScale(coor1[3][j].x))
                            .attr("cy", yScale(coor1[3][j].y))
                            .transition()
                            // .delay(500)
                            .duration(2000)
                            .attr("fill", color[coor1[4][j].label])
                            .attr("cx", padding.left + xScale(coor1[4][j].x))
                            .attr("cy", yScale(coor1[4][j].y))
                            .transition()
                            // .delay(500)
                            .duration(2000)
                            .attr("fill", color[coor1[5][j].label])
                            .attr("cx", padding.left + xScale(coor1[5][j].x))
                            .attr("cy", yScale(coor1[5][j].y))
                            .transition()
                            // .delay(500)
                            .duration(2000)
                            .attr("fill", color[coor1[6][j].label])
                            .attr("cx", padding.left + xScale(coor1[6][j].x))
                            .attr("cy", yScale(coor1[6][j].y))
                            .transition()
                            // .delay(500)
                            .duration(2000)
                            .attr("fill", color[coor1[7][j].label])
                            .attr("cx", padding.left + xScale(coor1[7][j].x))
                            .attr("cy", yScale(coor1[7][j].y))
                            .transition()
                            // .delay(500)
                            .duration(2000)
                            .attr("fill", color[coor1[8][j].label])
                            .attr("cx", padding.left + xScale(coor1[8][j].x))
                            .attr("cy", yScale(coor1[8][j].y))
                            .transition()
                            // .delay(500)
                            .duration(2000)
                            .attr("fill", color[coor1[9][j].label])
                            .attr("cx", padding.left + xScale(coor1[9][j].x))
                            .attr("cy", yScale(coor1[9][j].y))
                            .transition()
                            // .delay(500)
                            .duration(2000)
                            .attr("fill", color[coor1[10][j].label])
                            .attr("cx", padding.left + xScale(coor1[10][j].x))
                            .attr("cy", yScale(coor1[10][j].y))
                            .transition()
                            // .delay(500)
                            .duration(2000)
                            .attr("fill", color[coor1[11][j].label])
                            .attr("cx", padding.left + xScale(coor1[11][j].x))
                            .attr("cy", yScale(coor1[11][j].y))
                            .transition()
                            // .delay(500)
                            .duration(2000)
                            .attr("fill", color[coor1[12][j].label])
                            .attr("cx", padding.left + xScale(coor1[12][j].x))
                            .attr("cy", yScale(coor1[12][j].y))
                            .transition()
                            // .delay(500)
                            .duration(2000)
                            .attr("fill", color[coor1[13][j].label])
                            .attr("cx", padding.left + xScale(coor1[13][j].x))
                            .attr("cy", yScale(coor1[13][j].y))
                            .transition()
                            // .delay(500)
                            .duration(2000)
                            .attr("fill", color[coor1[14][j].label])
                            .attr("cx", padding.left + xScale(coor1[14][j].x))
                            .attr("cy", yScale(coor1[14][j].y))
                            .transition()
                            // .delay(500)
                            .duration(2000)
                            .attr("fill", color[coor1[15][j].label])
                            .attr("cx", padding.left + xScale(coor1[15][j].x))
                            .attr("cy", yScale(coor1[15][j].y))
                            .transition()
                            // .delay(500)
                            .duration(2000)
                            .attr("fill", color[coor1[16][j].label])
                            .attr("cx", padding.left + xScale(coor1[16][j].x))
                            .attr("cy", yScale(coor1[16][j].y))
                            .transition()
                            // .delay(500)
                            .duration(2000)
                            .attr("fill", color[coor1[17][j].label])
                            .attr("cx", padding.left + xScale(coor1[17][j].x))
                            .attr("cy", yScale(coor1[17][j].y))
                            .transition()
                            // .delay(500)
                            .duration(2000)
                            .attr("fill", color[coor1[18][j].label])
                            .attr("cx", padding.left + xScale(coor1[18][j].x))
                            .attr("cy", yScale(coor1[18][j].y))
                            .transition()
                            // .delay(500)
                            .duration(2000)
                            .attr("fill", color[coor1[19][j].label])
                            .attr("cx", padding.left + xScale(coor1[19][j].x))
                            .attr("cy", yScale(coor1[19][j].y))
                            .transition()
                            // .delay(500)
                            .duration(2000)
                            .attr("fill", color[coor1[20][j].label])
                            .attr("cx", padding.left + xScale(coor1[20][j].x))
                            .attr("cy", yScale(coor1[20][j].y))
                    }

                    ssvg2.append("text")
                            .attr("x", padding.left + 10)
                            .attr("y", heighta - padding.bottom)
                            // .attr("dx", 15)
                            // .attr("dy", "1em")
                            .attr('fill', 'black')
                            .attr('font-size', '10px')
                            .attr('text-anchor', 'middle')
                            .attr("font-family", "courier")
                            .text("第 1 轮")
                            .transition()
                            .duration(2000)
                            .text("第 2 轮")
                            .transition()
                            .duration(2000)
                            .text("第 3 轮")
                            .transition()
                            .duration(2000)
                            .text("第 4 轮")
                            .transition()
                            .duration(2000)
                            .text("第 5 轮")
                            .transition()
                            .duration(2000)
                            .text("第 6 轮")
                            .transition()
                            .duration(2000)
                            .text("第 7 轮")
                            .transition()
                            .duration(2000)
                            .text("第 8 轮")
                            .transition()
                            .duration(2000)
                            .text("第 9 轮")
                            .transition()
                            .duration(2000)
                            .text("第 10 轮")
                            .transition()
                            .duration(2000)
                            .text("第 11 轮")
                            .transition()
                            .duration(2000)
                            .text("第 12 轮")
                            .transition()
                            .duration(2000)
                            .text("第 13 轮")
                            .transition()
                            .duration(2000)
                            .text("第 14 轮")
                            .transition()
                            .duration(2000)
                            .text("第 15 轮")
                            .transition()
                            .duration(2000)
                            .text("第 16 轮")
                            .transition()
                            .duration(2000)
                            .text("第 17 轮")
                            .transition()
                            .duration(2000)
                            .text("第 18 轮")
                            .transition()
                            .duration(2000)
                            .text("第 19 轮")
                            .transition()
                            .duration(2000)
                            .text("第 20 轮")

                        for (var j = 0; j < 60; ++j) {
                            x = ssvg2.append('circle')
                                .attr("cx", padding.left + xScale(coor2[1][j].x))
                                .attr("cy", yScale(coor2[1][j].y))
                                .attr("r", 2)
                                .attr("fill", color[coor2[1][j].label])
                                // .ease('circle')
                                .transition()
                                // .delay(500)
                                .duration(2000)
                                .attr("fill", color[coor2[2][j].label])
                                .attr("cx", padding.left + xScale(coor2[2][j].x))
                                .attr("cy", yScale(coor2[2][j].y))
                                .transition()
                                // .delay(500)
                                .duration(2000)
                                .attr("fill", color[coor2[3][j].label])
                                .attr("cx", padding.left + xScale(coor2[3][j].x))
                                .attr("cy", yScale(coor2[3][j].y))
                                .transition()
                                // .delay(500)
                                .duration(2000)
                                .attr("fill", color[coor2[4][j].label])
                                .attr("cx", padding.left + xScale(coor2[4][j].x))
                                .attr("cy", yScale(coor2[4][j].y))
                                .transition()
                                // .delay(500)
                                .duration(2000)
                                .attr("fill", color[coor2[5][j].label])
                                .attr("cx", padding.left + xScale(coor2[5][j].x))
                                .attr("cy", yScale(coor2[5][j].y))
                                .transition()
                                // .delay(500)
                                .duration(2000)
                                .attr("fill", color[coor2[6][j].label])
                                .attr("cx", padding.left + xScale(coor2[6][j].x))
                                .attr("cy", yScale(coor2[6][j].y))
                                .transition()
                                // .delay(500)
                                .duration(2000)
                                .attr("fill", color[coor2[7][j].label])
                                .attr("cx", padding.left + xScale(coor2[7][j].x))
                                .attr("cy", yScale(coor2[7][j].y))
                                .transition()
                                // .delay(500)
                                .duration(2000)
                                .attr("fill", color[coor2[8][j].label])
                                .attr("cx", padding.left + xScale(coor2[8][j].x))
                                .attr("cy", yScale(coor2[8][j].y))
                                .transition()
                                // .delay(500)
                                .duration(2000)
                                .attr("fill", color[coor2[9][j].label])
                                .attr("cx", padding.left + xScale(coor2[9][j].x))
                                .attr("cy", yScale(coor2[9][j].y))
                                .transition()
                                // .delay(500)
                                .duration(2000)
                                .attr("fill", color[coor2[10][j].label])
                                .attr("cx", padding.left + xScale(coor2[10][j].x))
                                .attr("cy", yScale(coor2[10][j].y))
                                .transition()
                                // .delay(500)
                                .duration(2000)
                                .attr("fill", color[coor2[11][j].label])
                                .attr("cx", padding.left + xScale(coor2[11][j].x))
                                .attr("cy", yScale(coor2[11][j].y))
                                .transition()
                                // .delay(500)
                                .duration(2000)
                                .attr("fill", color[coor2[12][j].label])
                                .attr("cx", padding.left + xScale(coor2[12][j].x))
                                .attr("cy", yScale(coor2[12][j].y))
                                .transition()
                                // .delay(500)
                                .duration(2000)
                                .attr("fill", color[coor2[13][j].label])
                                .attr("cx", padding.left + xScale(coor2[13][j].x))
                                .attr("cy", yScale(coor2[13][j].y))
                                .transition()
                                // .delay(500)
                                .duration(2000)
                                .attr("fill", color[coor2[14][j].label])
                                .attr("cx", padding.left + xScale(coor2[14][j].x))
                                .attr("cy", yScale(coor2[14][j].y))
                                .transition()
                                // .delay(500)
                                .duration(2000)
                                .attr("fill", color[coor2[15][j].label])
                                .attr("cx", padding.left + xScale(coor2[15][j].x))
                                .attr("cy", yScale(coor2[15][j].y))
                                .transition()
                                // .delay(500)
                                .duration(2000)
                                .attr("fill", color[coor2[16][j].label])
                                .attr("cx", padding.left + xScale(coor2[16][j].x))
                                .attr("cy", yScale(coor2[16][j].y))
                                .transition()
                                // .delay(500)
                                .duration(2000)
                                .attr("fill", color[coor2[17][j].label])
                                .attr("cx", padding.left + xScale(coor2[17][j].x))
                                .attr("cy", yScale(coor2[17][j].y))
                                .transition()
                                // .delay(500)
                                .duration(2000)
                                .attr("fill", color[coor2[18][j].label])
                                .attr("cx", padding.left + xScale(coor2[18][j].x))
                                .attr("cy", yScale(coor2[18][j].y))
                                .transition()
                                // .delay(500)
                                .duration(2000)
                                .attr("fill", color[coor2[19][j].label])
                                .attr("cx", padding.left + xScale(coor2[19][j].x))
                                .attr("cy", yScale(coor2[19][j].y))
                                .transition()
                                // .delay(500)
                                .duration(2000)
                                .attr("fill", color[coor2[20][j].label])
                                .attr("cx", padding.left + xScale(coor2[20][j].x))
                                .attr("cy", yScale(coor2[20][j].y))
                        }

                        ssvg3.append("text")
                            .attr("x", padding.left + 10)
                            .attr("y", heighta - padding.bottom)
                            // .attr("dx", 15)
                            // .attr("dy", "1em")
                            .attr('fill', 'black')
                            .attr('font-size', '10px')
                            .attr('text-anchor', 'middle')
                            .attr("font-family", "courier")
                            .text("第 1 轮")
                            .transition()
                            .duration(2000)
                            .text("第 2 轮")
                            .transition()
                            .duration(2000)
                            .text("第 3 轮")
                            .transition()
                            .duration(2000)
                            .text("第 4 轮")
                            .transition()
                            .duration(2000)
                            .text("第 5 轮")
                            .transition()
                            .duration(2000)
                            .text("第 6 轮")
                            .transition()
                            .duration(2000)
                            .text("第 7 轮")
                            .transition()
                            .duration(2000)
                            .text("第 8 轮")
                            .transition()
                            .duration(2000)
                            .text("第 9 轮")
                            .transition()
                            .duration(2000)
                            .text("第 10 轮")
                            .transition()
                            .duration(2000)
                            .text("第 11 轮")
                            .transition()
                            .duration(2000)
                            .text("第 12 轮")
                            .transition()
                            .duration(2000)
                            .text("第 13 轮")
                            .transition()
                            .duration(2000)
                            .text("第 14 轮")
                            .transition()
                            .duration(2000)
                            .text("第 15 轮")
                            .transition()
                            .duration(2000)
                            .text("第 16 轮")
                            .transition()
                            .duration(2000)
                            .text("第 17 轮")
                            .transition()
                            .duration(2000)
                            .text("第 18 轮")
                            .transition()
                            .duration(2000)
                            .text("第 19 轮")
                            .transition()
                            .duration(2000)
                            .text("第 20 轮")

                        for (var j = 0; j < 60; ++j) {
                            x = ssvg3.append('circle')
                                .attr("cx", padding.left + xScale(coor3[1][j].x))
                                .attr("cy", yScale(coor3[1][j].y))
                                .attr("r", 2)
                                .attr("fill", color[coor3[1][j].label])
                                // .ease('circle')
                                .transition()
                                // .delay(500)
                                .duration(2000)
                                .attr("fill", color[coor3[2][j].label])
                                .attr("cx", padding.left + xScale(coor3[2][j].x))
                                .attr("cy", yScale(coor3[2][j].y))
                                .transition()
                                // .delay(500)
                                .duration(2000)
                                .attr("fill", color[coor3[3][j].label])
                                .attr("cx", padding.left + xScale(coor3[3][j].x))
                                .attr("cy", yScale(coor3[3][j].y))
                                .transition()
                                // .delay(500)
                                .duration(2000)
                                .attr("fill", color[coor3[4][j].label])
                                .attr("cx", padding.left + xScale(coor3[4][j].x))
                                .attr("cy", yScale(coor3[4][j].y))
                                .transition()
                                // .delay(500)
                                .duration(2000)
                                .attr("fill", color[coor3[5][j].label])
                                .attr("cx", padding.left + xScale(coor3[5][j].x))
                                .attr("cy", yScale(coor3[5][j].y))
                                .transition()
                                // .delay(500)
                                .duration(2000)
                                .attr("fill", color[coor3[6][j].label])
                                .attr("cx", padding.left + xScale(coor3[6][j].x))
                                .attr("cy", yScale(coor3[6][j].y))
                                .transition()
                                // .delay(500)
                                .duration(2000)
                                .attr("fill", color[coor3[7][j].label])
                                .attr("cx", padding.left + xScale(coor3[7][j].x))
                                .attr("cy", yScale(coor3[7][j].y))
                                .transition()
                                // .delay(500)
                                .duration(2000)
                                .attr("fill", color[coor3[8][j].label])
                                .attr("cx", padding.left + xScale(coor3[8][j].x))
                                .attr("cy", yScale(coor3[8][j].y))
                                .transition()
                                // .delay(500)
                                .duration(2000)
                                .attr("fill", color[coor3[9][j].label])
                                .attr("cx", padding.left + xScale(coor3[9][j].x))
                                .attr("cy", yScale(coor3[9][j].y))
                                .transition()
                                // .delay(500)
                                .duration(2000)
                                .attr("fill", color[coor3[10][j].label])
                                .attr("cx", padding.left + xScale(coor3[10][j].x))
                                .attr("cy", yScale(coor3[10][j].y))
                                .transition()
                                // .delay(500)
                                .duration(2000)
                                .attr("fill", color[coor3[11][j].label])
                                .attr("cx", padding.left + xScale(coor3[11][j].x))
                                .attr("cy", yScale(coor3[11][j].y))
                                .transition()
                                // .delay(500)
                                .duration(2000)
                                .attr("fill", color[coor3[12][j].label])
                                .attr("cx", padding.left + xScale(coor3[12][j].x))
                                .attr("cy", yScale(coor3[12][j].y))
                                .transition()
                                // .delay(500)
                                .duration(2000)
                                .attr("fill", color[coor3[13][j].label])
                                .attr("cx", padding.left + xScale(coor3[13][j].x))
                                .attr("cy", yScale(coor3[13][j].y))
                                .transition()
                                // .delay(500)
                                .duration(2000)
                                .attr("fill", color[coor3[14][j].label])
                                .attr("cx", padding.left + xScale(coor3[14][j].x))
                                .attr("cy", yScale(coor3[14][j].y))
                                .transition()
                                // .delay(500)
                                .duration(2000)
                                .attr("fill", color[coor3[15][j].label])
                                .attr("cx", padding.left + xScale(coor3[15][j].x))
                                .attr("cy", yScale(coor3[15][j].y))
                                .transition()
                                // .delay(500)
                                .duration(2000)
                                .attr("fill", color[coor3[16][j].label])
                                .attr("cx", padding.left + xScale(coor3[16][j].x))
                                .attr("cy", yScale(coor3[16][j].y))
                                .transition()
                                // .delay(500)
                                .duration(2000)
                                .attr("fill", color[coor3[17][j].label])
                                .attr("cx", padding.left + xScale(coor3[17][j].x))
                                .attr("cy", yScale(coor3[17][j].y))
                                .transition()
                                // .delay(500)
                                .duration(2000)
                                .attr("fill", color[coor3[18][j].label])
                                .attr("cx", padding.left + xScale(coor3[18][j].x))
                                .attr("cy", yScale(coor3[18][j].y))
                                .transition()
                                // .delay(500)
                                .duration(2000)
                                .attr("fill", color[coor3[19][j].label])
                                .attr("cx", padding.left + xScale(coor3[19][j].x))
                                .attr("cy", yScale(coor3[19][j].y))
                                .transition()
                                // .delay(500)
                                .duration(2000)
                                .attr("fill", color[coor3[20][j].label])
                                .attr("cx", padding.left + xScale(coor3[20][j].x))
                                .attr("cy", yScale(coor3[20][j].y))
                        }
                        ssvg4.append("text")
                            .attr("x", padding.left + 10)
                            .attr("y", heighta - padding.bottom)
                            // .attr("dx", 15)
                            // .attr("dy", "1em")
                            .attr('fill', 'black')
                            .attr('font-size', '10px')
                            .attr('text-anchor', 'middle')
                            .attr("font-family", "courier")
                            .text("第 1 轮")
                            .transition()
                            .duration(2000)
                            .text("第 2 轮")
                            .transition()
                            .duration(2000)
                            .text("第 3 轮")
                            .transition()
                            .duration(2000)
                            .text("第 4 轮")
                            .transition()
                            .duration(2000)
                            .text("第 5 轮")
                            .transition()
                            .duration(2000)
                            .text("第 6 轮")
                            .transition()
                            .duration(2000)
                            .text("第 7 轮")
                            .transition()
                            .duration(2000)
                            .text("第 8 轮")
                            .transition()
                            .duration(2000)
                            .text("第 9 轮")
                            .transition()
                            .duration(2000)
                            .text("第 10 轮")
                            .transition()
                            .duration(2000)
                            .text("第 11 轮")
                            .transition()
                            .duration(2000)
                            .text("第 12 轮")
                            .transition()
                            .duration(2000)
                            .text("第 13 轮")
                            .transition()
                            .duration(2000)
                            .text("第 14 轮")
                            .transition()
                            .duration(2000)
                            .text("第 15 轮")
                            .transition()
                            .duration(2000)
                            .text("第 16 轮")
                            .transition()
                            .duration(2000)
                            .text("第 17 轮")
                            .transition()
                            .duration(2000)
                            .text("第 18 轮")
                            .transition()
                            .duration(2000)
                            .text("第 19 轮")
                            .transition()
                            .duration(2000)
                            .text("第 20 轮")

                        for (var j = 0; j < 64; ++j) {
                            x = ssvg4.append('circle')
                                .attr("cx", padding.left + xScale(coor4[1][j].x))
                                .attr("cy", yScale(coor4[1][j].y))
                                .attr("r", 2)
                                .attr("fill", color[coor4[1][j].label])
                                // .ease('circle')
                                .transition()
                                // .delay(500)
                                .duration(2000)
                                .attr("fill", color[coor4[2][j].label])
                                .attr("cx", padding.left + xScale(coor4[2][j].x))
                                .attr("cy", yScale(coor4[2][j].y))
                                .transition()
                                // .delay(500)
                                .duration(2000)
                                .attr("fill", color[coor4[3][j].label])
                                .attr("cx", padding.left + xScale(coor4[3][j].x))
                                .attr("cy", yScale(coor4[3][j].y))
                                .transition()
                                // .delay(500)
                                .duration(2000)
                                .attr("fill", color[coor4[4][j].label])
                                .attr("cx", padding.left + xScale(coor4[4][j].x))
                                .attr("cy", yScale(coor4[4][j].y))
                                .transition()
                                // .delay(500)
                                .duration(2000)
                                .attr("fill", color[coor4[5][j].label])
                                .attr("cx", padding.left + xScale(coor4[5][j].x))
                                .attr("cy", yScale(coor4[5][j].y))
                                .transition()
                                // .delay(500)
                                .duration(2000)
                                .attr("fill", color[coor4[6][j].label])
                                .attr("cx", padding.left + xScale(coor4[6][j].x))
                                .attr("cy", yScale(coor4[6][j].y))
                                .transition()
                                // .delay(500)
                                .duration(2000)
                                .attr("fill", color[coor4[7][j].label])
                                .attr("cx", padding.left + xScale(coor4[7][j].x))
                                .attr("cy", yScale(coor4[7][j].y))
                                .transition()
                                // .delay(500)
                                .duration(2000)
                                .attr("fill", color[coor4[8][j].label])
                                .attr("cx", padding.left + xScale(coor4[8][j].x))
                                .attr("cy", yScale(coor4[8][j].y))
                                .transition()
                                // .delay(500)
                                .duration(2000)
                                .attr("fill", color[coor4[9][j].label])
                                .attr("cx", padding.left + xScale(coor4[9][j].x))
                                .attr("cy", yScale(coor4[9][j].y))
                                .transition()
                                // .delay(500)
                                .duration(2000)
                                .attr("fill", color[coor4[10][j].label])
                                .attr("cx", padding.left + xScale(coor4[10][j].x))
                                .attr("cy", yScale(coor4[10][j].y))
                                .transition()
                                // .delay(500)
                                .duration(2000)
                                .attr("fill", color[coor4[11][j].label])
                                .attr("cx", padding.left + xScale(coor4[11][j].x))
                                .attr("cy", yScale(coor4[11][j].y))
                                .transition()
                                // .delay(500)
                                .duration(2000)
                                .attr("fill", color[coor4[12][j].label])
                                .attr("cx", padding.left + xScale(coor4[12][j].x))
                                .attr("cy", yScale(coor4[12][j].y))
                                .transition()
                                // .delay(500)
                                .duration(2000)
                                .attr("fill", color[coor4[13][j].label])
                                .attr("cx", padding.left + xScale(coor4[13][j].x))
                                .attr("cy", yScale(coor4[13][j].y))
                                .transition()
                                // .delay(500)
                                .duration(2000)
                                .attr("fill", color[coor4[14][j].label])
                                .attr("cx", padding.left + xScale(coor4[14][j].x))
                                .attr("cy", yScale(coor4[14][j].y))
                                .transition()
                                // .delay(500)
                                .duration(2000)
                                .attr("fill", color[coor4[15][j].label])
                                .attr("cx", padding.left + xScale(coor4[15][j].x))
                                .attr("cy", yScale(coor4[15][j].y))
                                .transition()
                                // .delay(500)
                                .duration(2000)
                                .attr("fill", color[coor4[16][j].label])
                                .attr("cx", padding.left + xScale(coor4[16][j].x))
                                .attr("cy", yScale(coor4[16][j].y))
                                .transition()
                                // .delay(500)
                                .duration(2000)
                                .attr("fill", color[coor4[17][j].label])
                                .attr("cx", padding.left + xScale(coor4[17][j].x))
                                .attr("cy", yScale(coor4[17][j].y))
                                .transition()
                                // .delay(500)
                                .duration(2000)
                                .attr("fill", color[coor4[18][j].label])
                                .attr("cx", padding.left + xScale(coor4[18][j].x))
                                .attr("cy", yScale(coor4[18][j].y))
                                .transition()
                                // .delay(500)
                                .duration(2000)
                                .attr("fill", color[coor4[19][j].label])
                                .attr("cx", padding.left + xScale(coor4[19][j].x))
                                .attr("cy", yScale(coor4[19][j].y))
                                .transition()
                                // .delay(500)
                                .duration(2000)
                                .attr("fill", color[coor4[20][j].label])
                                .attr("cx", padding.left + xScale(coor4[20][j].x))
                                .attr("cy", yScale(coor4[20][j].y))
                        }

                        ssvg5.append("text")
                            .attr("x", padding.left + 10)
                            .attr("y", heighta - padding.bottom)
                            // .attr("dx", 15)
                            // .attr("dy", "1em")
                            .attr('fill', 'black')
                            .attr('font-size', '10px')
                            .attr('text-anchor', 'middle')
                            .attr("font-family", "courier")
                            .text("第 1 轮")
                            .transition()
                            .duration(2000)
                            .text("第 2 轮")
                            .transition()
                            .duration(2000)
                            .text("第 3 轮")
                            .transition()
                            .duration(2000)
                            .text("第 4 轮")
                            .transition()
                            .duration(2000)
                            .text("第 5 轮")
                            .transition()
                            .duration(2000)
                            .text("第 6 轮")
                            .transition()
                            .duration(2000)
                            .text("第 7 轮")
                            .transition()
                            .duration(2000)
                            .text("第 8 轮")
                            .transition()
                            .duration(2000)
                            .text("第 9 轮")
                            .transition()
                            .duration(2000)
                            .text("第 10 轮")
                            .transition()
                            .duration(2000)
                            .text("第 11 轮")
                            .transition()
                            .duration(2000)
                            .text("第 12 轮")
                            .transition()
                            .duration(2000)
                            .text("第 13 轮")
                            .transition()
                            .duration(2000)
                            .text("第 14 轮")
                            .transition()
                            .duration(2000)
                            .text("第 15 轮")
                            .transition()
                            .duration(2000)
                            .text("第 16 轮")
                            .transition()
                            .duration(2000)
                            .text("第 17 轮")
                            .transition()
                            .duration(2000)
                            .text("第 18 轮")
                            .transition()
                            .duration(2000)
                            .text("第 19 轮")
                            .transition()
                            .duration(2000)
                            .text("第 20 轮")

                        for (var j = 0; j < 60; ++j) {
                            x = ssvg5.append('circle')
                                .attr("cx", padding.left + xScale(coor5[1][j].x))
                                .attr("cy", yScale(coor5[1][j].y))
                                .attr("r", 2)
                                .attr("fill", color[coor5[1][j].label])
                                // .ease('circle')
                                .transition()
                                // .delay(500)
                                .duration(2000)
                                .attr("fill", color[coor5[2][j].label])
                                .attr("cx", padding.left + xScale(coor5[2][j].x))
                                .attr("cy", yScale(coor5[2][j].y))
                                .transition()
                                // .delay(500)
                                .duration(2000)
                                .attr("fill", color[coor5[3][j].label])
                                .attr("cx", padding.left + xScale(coor5[3][j].x))
                                .attr("cy", yScale(coor5[3][j].y))
                                .transition()
                                // .delay(500)
                                .duration(2000)
                                .attr("fill", color[coor5[4][j].label])
                                .attr("cx", padding.left + xScale(coor5[4][j].x))
                                .attr("cy", yScale(coor5[4][j].y))
                                .transition()
                                // .delay(500)
                                .duration(2000)
                                .attr("fill", color[coor5[5][j].label])
                                .attr("cx", padding.left + xScale(coor5[5][j].x))
                                .attr("cy", yScale(coor5[5][j].y))
                                .transition()
                                // .delay(500)
                                .duration(2000)
                                .attr("fill", color[coor5[6][j].label])
                                .attr("cx", padding.left + xScale(coor5[6][j].x))
                                .attr("cy", yScale(coor5[6][j].y))
                                .transition()
                                // .delay(500)
                                .duration(2000)
                                .attr("fill", color[coor5[7][j].label])
                                .attr("cx", padding.left + xScale(coor5[7][j].x))
                                .attr("cy", yScale(coor5[7][j].y))
                                .transition()
                                // .delay(500)
                                .duration(2000)
                                .attr("fill", color[coor5[8][j].label])
                                .attr("cx", padding.left + xScale(coor5[8][j].x))
                                .attr("cy", yScale(coor5[8][j].y))
                                .transition()
                                // .delay(500)
                                .duration(2000)
                                .attr("fill", color[coor5[9][j].label])
                                .attr("cx", padding.left + xScale(coor5[9][j].x))
                                .attr("cy", yScale(coor5[9][j].y))
                                .transition()
                                // .delay(500)
                                .duration(2000)
                                .attr("fill", color[coor5[10][j].label])
                                .attr("cx", padding.left + xScale(coor5[10][j].x))
                                .attr("cy", yScale(coor5[10][j].y))
                                .transition()
                                // .delay(500)
                                .duration(2000)
                                .attr("fill", color[coor5[11][j].label])
                                .attr("cx", padding.left + xScale(coor5[11][j].x))
                                .attr("cy", yScale(coor5[11][j].y))
                                .transition()
                                // .delay(500)
                                .duration(2000)
                                .attr("fill", color[coor5[12][j].label])
                                .attr("cx", padding.left + xScale(coor5[12][j].x))
                                .attr("cy", yScale(coor5[12][j].y))
                                .transition()
                                // .delay(500)
                                .duration(2000)
                                .attr("fill", color[coor5[13][j].label])
                                .attr("cx", padding.left + xScale(coor5[13][j].x))
                                .attr("cy", yScale(coor5[13][j].y))
                                .transition()
                                // .delay(500)
                                .duration(2000)
                                .attr("fill", color[coor5[14][j].label])
                                .attr("cx", padding.left + xScale(coor5[14][j].x))
                                .attr("cy", yScale(coor5[14][j].y))
                                .transition()
                                // .delay(500)
                                .duration(2000)
                                .attr("fill", color[coor5[15][j].label])
                                .attr("cx", padding.left + xScale(coor5[15][j].x))
                                .attr("cy", yScale(coor5[15][j].y))
                                .transition()
                                // .delay(500)
                                .duration(2000)
                                .attr("fill", color[coor5[16][j].label])
                                .attr("cx", padding.left + xScale(coor5[16][j].x))
                                .attr("cy", yScale(coor5[16][j].y))
                                .transition()
                                // .delay(500)
                                .duration(2000)
                                .attr("fill", color[coor5[17][j].label])
                                .attr("cx", padding.left + xScale(coor5[17][j].x))
                                .attr("cy", yScale(coor5[17][j].y))
                                .transition()
                                // .delay(500)
                                .duration(2000)
                                .attr("fill", color[coor5[18][j].label])
                                .attr("cx", padding.left + xScale(coor5[18][j].x))
                                .attr("cy", yScale(coor5[18][j].y))
                                .transition()
                                // .delay(500)
                                .duration(2000)
                                .attr("fill", color[coor5[19][j].label])
                                .attr("cx", padding.left + xScale(coor5[19][j].x))
                                .attr("cy", yScale(coor5[19][j].y))
                                .transition()
                                // .delay(500)
                                .duration(2000)
                                .attr("fill", color[coor5[20][j].label])
                                .attr("cx", padding.left + xScale(coor5[20][j].x))
                                .attr("cy", yScale(coor5[20][j].y))
                        }
                    })
                })
            })
        })
    })
})